### ISSUE TITLE
Potential rephrase of #4

### ISSUE THREAD

**Issue by Alch-Emi** [Widdershin/programmers-oath#149]
This is a super small thing, but it kinda bugged me a little the first time I read the oath.  Tenet number four currently says:

> I will respect the privacy of my users, for their information is not disclosed to me that the world may know.

but I feel like this doesn't actually speak to the majority of privacy violations.  A lot of the time, a privacy violation doesn't come from a user's information being disclosed to the world at large, but from developers collecting more data than they need in order to meet the user's goals, in an effort to complete some goal of their own.

For example, GameCo might need a user's birthday to comply with the the local law, but also decides to collect the user's contacts, which doesn't meet any real wants of the users', but is used to help advertise the game, at the cost of the privacy of the user, and the user's friends.

Another example that might be a bit more relevant to ethics minded devs:  Say Devan designs a chat bot and introduces it to \*the world\*.  Because of it's nature, the bot can read a lot of different chatrooms, and has access to lots of user data.  It would be unethical for Devan to take advantage of this to read their user's chat messages, although this doesn't clearly violate the 4th tenet, since the user's data isn't exposed to the world.

One last example, some company, lets say Shmoogle, has been trusted with a lot of user data.  It would be unethical to feed that data into an advertising algorithm for profit.  Not a single human more is aware of the user's data, since it's all handled by the :sparkles: \~algorithm\~ :sparkles:, but it's still clearly unethical, not because of who the data is being exposed to, but because the data is being used to an end that the users did not disclose it for.

Tenet 4 *could* be interpreted to cover these cases, but I feel like it's pretty subjective, and someone tempted into doing this could easily dismiss it.  I'm proposing the following change to Tenet 4 to hopefully make this a little more clear:

> I will respect the privacy of my users, and use their data only to the end that it was entrusted to me for.

It's a small change, but I think it speaks to the above dilemas well, while still keeping the emphasis of the original:

* User data is granted with trust, and that is a privilege
* Users have their own goals when disclosing information, that may differ from what I would like to use it for
* User privacy must be respected, and abusing their data is a violation of that.

That said, I'm completely open to feedback.  I've opened this as an issue instead of as a PR because I'd rather frame it as a potential area for change with a WIP idea than me presenting a finished solution, so please let me know if there are things you think this phrasing fails to cover, misrepresents, or is confusingly worded on, or if there are other ideas you think it should cover.

Looking forward to hearing back,

Emi <3

**Comment by Widdershin** [comment]
Hey sorry I think I totally missed this issue.

I like this rephrase a lot, was looking at the original today and I think this is a lot better. Would happily accept a PR along these lines.
