### ISSUE TITLE
Pragmatism over idealism?

### ISSUE THREAD

**Issue by simontegg** [Widdershin/programmers-oath#2]
I think there's a case for paid work to be pragmatic but this is more appropriate for a professional code of conduct than an oath. 

Since programming is also an art I'm not going to swear an oath to pragmatism!

**Comment by Widdershin** [comment]
I agree, I'll remove it. Thanks for the feedback. 😸

**Comment by Widdershin** [comment]
@simontegg if you're interested, I would love to invite you to be a collaborator on this repo. It wouldn't obligate you to contribute, but I value your input and I'd like to have collaborators that represent a diverse set of viewpoints.

**Comment by simontegg** [comment]
cool
