### ISSUE TITLE
How to publicly sign/swear?

### ISSUE THREAD

**Issue by Widdershin** [Widdershin/programmers-oath#3]
@mermop suggested that we make a website to list signatories, like the [Agile Manifesto](http://agilemanifesto.org/display/index.html).

I like this idea. Are there any considerations? Is there anything lacking about the current approach we could improve on?

**Comment by soundasleep** [comment]
What if you could have a button that you put on your projects, like the travis-ci badges etc?

**Comment by zakm** [comment]
Maybe you could fork it and sign with your private key?

**Comment by mo-g** [comment]
If one is to treat this as an 'oath' of sorts, then a PGP signature is efficient and effective.

A more integrated solution (I'm sure there are many coders who do not make huge use of PGP) would be a 'SIGNATURES.md' to which signatories append their github ID to with a Pull Request. Downside is - if this becomes as popular as one would hope, this would require a lot of effort from repo contributors to merge all the PR's.

**Comment by Widdershin** [comment]
What would the workflow for using PGP to sign be? I've never used PGP before for something like this.

Versioning is definitely a problem. We could have a SIGNATURES file with Github IDs and the commit SHA they're signing for, that would be probably the simplest solution. If this oath becomes so popular that merging PRs becomes a nightmare, we could always make a little web service to make it easier.

We could also have a version number for the oath itself. Without digging into the arguments around SemVer, it seems like we would at least want to differentiate between changes to the meaning of the oath and formatting changes.

**Comment by mo-g** [comment]
Commit SHA seems cleaner than committing to a versioning system at this point. Would suggest a simple space-separated format, as in:

`mo-g bea1d307f41ac5801df4b975f100d6cc0cb1a21a`.

If you're happy with that as a solution, I'd be proud to throw up a PR and be the first person to publicly sign the oath. ;)

**Comment by Widdershin** [comment]
Happy enough for the moment, let's solve any additional issues as they come up.

**Comment by Widdershin** [comment]
I'll close this issue, as we now have a mechanism for publicly signing. That doesn't mean the discussion is closed, if anyone has any further thoughts or ideas, please feel free to continue using this issue.

**Comment by mo-g** [comment]
I assume that in a case where a major change had taken place - you'd happily merge a PR to replace an old commit hash to a newer one?

**Comment by Widdershin** [comment]
Yes indeed, if anyone wants to re-sign with a different hash I'll happily merge that.

I would also be totally fine with it if someone wanted to go back to an older hash.

**Comment by Widdershin** [comment]
Hey @mo-g, thanks for all the help so far. I've invited you to be a collaborator.

If you're interested, could you please merge signature pull requests when you have time?

I ask that for the moment, you hold off on merging any changes to the oath itself until I've had a look at the pull request.

Looks like we might need to build this web service sooner than I thought 😊

**Comment by mo-g** [comment]
Yeah, no kidding.

And sure - happy to stick to sigs for now. :)
