### ISSUE TITLE
Item 5 could be two items

### ISSUE THREAD

**Issue by brylie** [Widdershin/programmers-oath#37]
The text in item 5 seems like two separate items. Both items are important, but they seem somewhat distinct. 

> 5. I will tread most carefully in matters of life or death. I will be humble and recognize that I will make mistakes.

The '*I will be humble and recognize that I will make mistakes.*' seems more directly related to item 3 '*I will not be ashamed to say "I don't know", and I will ask for help when I am stuck.*'

**Comment by mo-g** [comment]
This seems a reasonable argument. Throw up a PR? :smile:

**Comment by brylie** [comment]
PR opened :-)
