### ISSUE TITLE
Compare to an older Programmer's Oath

### ISSUE THREAD

**Issue by vassudanagunta** [Widdershin/programmers-oath#88]
This [programmer's oath](https://dionyziz.com/oath/) predates this one [by more than four years](https://github.com/dionyziz/oath/commit/77b539055a4c12e299dd62457fc1ff249fa3427c). 

Here's [the Hacker News discussion of it](https://news.ycombinator.com/item?id=6886399).

It is worth comparing, as well as reaching out to its author for input, collaboration or a possible merging. 

@Widdershin, there is so much overlap. Is the oath you wrote derivative, or is the similarity just a reflection of shared values/truths?

**Comment by dionyziz** [comment]
Glad to see other oath's popping up after mine! I don't know if this one was inspired by what I wrote, but it seems that both of them were inspired by the Engineer's oath as well as the Hippocratic oath, so I wouldn't find it surprising if a lot of elements are common.

**Comment by pachunka** [comment]
That original oath is very nice indeed., solves a lot of the issues being brought up with this one, too.

I think it's pretty cool that a separate effort arrived at very similar values. I think it's encouraging.

As to whether this newer effort is derivative - I find it hard to believe that somebody interested in establishing an ethics-driven oath would had made an overt derivation without giving credit. There'd be no point.

**Comment by pachunka** [comment]
Oh hey it's Dio! =D

**Comment by Widdershin** [comment]
>  Is the oath you wrote derivative, or is the similarity just a reflection of shared values/truths?

I hadn't seen @dionyziz's oath when I wrote this one, found out about it from this issue 😄 

> Glad to see other oaths popping up after mine! I don't know if this one was inspired by what I wrote, but it seems that both of them were inspired by the Engineer's oath as well as the Hippocratic oath, so I wouldn't find it surprising if a lot of elements are common.

Yeah, this is pretty much it!

> As to whether this newer effort is derivative - I find it hard to believe that somebody interested in establishing an ethics-driven oath would had made an overt derivation without giving credit. There'd be no point.

Thanks for assuming the best of me, rare to see on the internet 😸

**Comment by dionyziz** [comment]
Hey pach! 🐱

**Comment by vassudanagunta** [comment]
@Widdershin never meant to insinuate, just asked straight up 🙂

Part of being ethical is speaking up when there’s doubt. Politeness is great, but not at the expense of truth and openness. For example, discrimination and sexual harassment of women in tech and elsewhere has persisted for so long and continues to persist because too many men claiming to be pro-equality stay silent (or even play along to gain social cred) when they observe unacceptable behavior.

**Comment by Widdershin** [comment]
Sorry, I must have not have chosen my words well. I never got the
impression that anybody insinuated any wrongdoing on my part, and for that
I am grateful.

Vas, I appreciate you asking straight up and for bringing this excellent
piece of prior art to my attention 😊

**Comment by mo-g** [comment]
> Part of being ethical is speaking up when there’s doubt.

It's part of doing no harm, to decide when to query, and when to remain silent. The old British joke `They died in a fire. At sea parks. YEAH, WITH THE WHALES AND STUFF.` Sometimes, no matter how strong the doubt may be, tact takes precedence in order to avoid harm. But, if the continued doubt causes harm (as in the case of `wait, does she get paid less than me?`) then the moral duty to query takes precedence over a manager's snubbed nose.

I'm sure you meant that, but thought it deserved explicit codification.

**Comment by vassudanagunta** [comment]
@mo-g sure. Except that too many people use such an excuse in bad faith. Look around at all the injustice in our world. There's far far more self-serving silence than there is wise restraint. There's plenty of virtue signaling because that comes cheap. Unfortunately I'm not sure this oath is anything other than that. The stuff that matters involves sacrifice.

Words said fifty years ago but could just as well have been said this morning, words said by a man many love to quote (more virtual signaling) but few actually understand:

> History will have to record that the greatest tragedy of this period of social transition was not the strident clamor of the bad people, but the appalling silence of the good people.

> A time comes when silence is betrayal. Even when pressed by the demands of inner truth, men do not easily assume the task of opposing their government's policy, especially in time of war. Nor does the human spirit move without great difficulty against all the apathy of conformist thought within one's own bosom and in the surrounding world. Moreover, when the issues at hand seem as perplexing as they often do in the case of dreadful conflict, we are always on the verge of being mesmerized by uncertainty. But we must move on.

> This hour in history needs a dedicated circle of transformed nonconformists. Our planet teeters on the brink of annihilation; dangerous passions of pride, hatred, and selfishness are enthroned in our lives; and men do reverence before false gods of nationalism and materialism. The saving of our world from pending doom will come, not through the complacent adjustment of the conforming majority, but through the creative maladjustment of a nonconforming minority.

~ Martin Luther King, Jr.
