### ISSUE TITLE
Signing a changing oath.. versioning required?

### ISSUE THREAD

**Issue by aschrijver** [Widdershin/programmers-oath#92]
When you sign the oath, you sign the current version of it.. but the oath can be changed at any time by a PR. What if someone that signed does not agree to a future revision of the oath?
Shouldn't there be some kind of versioning scheme?

**Comment by Widdershin** [comment]
> Shouldn't there be some kind of versioning scheme?

Yes indeed, this is the purpose of the commit hash that accompanies each signature, it indicates which version of the oath a user signed.

If the oath changes you're welcome to re-sign with a new version by update the hash that accompanies your signature.

For more discussion on this issue see #3 and #18.

Happy with that?

**Comment by aschrijver** [comment]
Entirely happy :)

**Comment by mo-g** [comment]
Will do - I'm reopening the issue so that there's continuity between the two. :)

Edit: Won't be till tonight/tomorrow now, it's gone 1AM and I need to be up at *some* point.

**Comment by vassudanagunta** [comment]
@no-g I’d also add that you recommend people star/watch the repo so they get updated on changes. Side benefit is that everyone who signs also stars and the word gets spread.

**Comment by manuel-uberti** [comment]
Probably a silly question: is it necessary to re-sign the oath at ever change?

**Comment by aschrijver** [comment]
I think this is voluntary.. your previous signature is tagged to the commit state at that particular time.. tagged to that 'version'. But if you like the improvements that have been made since that time, you could re-sign :)

**Comment by manuel-uberti** [comment]
https://github.com/Widdershin/programmers-oath/pull/95

Done :)
